# Usign the Clean Blog theme

title: The CogML Seminar
author: rachine
email: riadrachid3@gmail.com
description: When Cognitive Sciences Meet Artificial Intelligence
baseurl: ""
url: "https://CogML-seminar.github.io/"
github_username:  rachine

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]

name: The CogML Seminar
gems:
  - jekyll-feed
  - jekyll-paginate
